function CMat = C(in1)
%C
%    CMat = C(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Oct-2024 18:03:03

q1 = in1(1,:);
CMat = sin(q1).*(9.81e+2./2.0e+2);
end
