function p0 = p0(in1,dt)
%P0
%    P0 = P0(IN1,DT)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Oct-2024 18:03:03

dq1 = in1(2,:);
q1 = in1(1,:);
p0 = dq1.*3.339583333333333e-1+dt.*sin(q1).*(9.81e+2./4.0e+2);
end
