function out1 = pBase(in1)
%pBase
%    OUT1 = pBase(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Feb-2025 15:48:47

q1 = in1(1,:);
q2 = in1(2,:);
out1 = [q1;0.0;q2];
end
