function out1 = pHead(in1)
%pHead
%    OUT1 = pHead(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Feb-2025 15:48:47

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
out1 = [q1+t2.*5.266999999999999e-3+t3.*4.49869e-1;0.0;q2+t2.*4.49869e-1-t3.*5.266999999999999e-3];
end
