function out1 = pHipPitch(in1)
%pHipPitch
%    OUT1 = pHipPitch(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Feb-2025 15:48:47

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
out1 = [q1-sin(q3).*1.027e-1;0.0;q2-cos(q3).*1.027e-1];
end
