function out1 = pKnee(in1)
%pKnee
%    OUT1 = pKnee(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    06-Feb-2025 15:48:47

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q3);
t3 = cos(q4);
t4 = sin(q3);
t5 = sin(q4);
et1 = q1-t4.*1.027e-1-t2.*t3.*2.326096781009612e-6-t2.*t5.*3.365957524222114e-1;
et2 = t3.*t4.*(-3.365957524222114e-1)+t4.*t5.*2.326096781009612e-6;
et3 = q2-t2.*1.027e-1-t2.*t3.*3.365957524222114e-1+t2.*t5.*2.326096781009612e-6;
et4 = t3.*t4.*2.326096781009612e-6+t4.*t5.*3.365957524222114e-1;
out1 = [et1+et2;0.0;et3+et4];
end
