function pJ1 = pJ1(in1)
%pJ1
%    pJ1 = pJ1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Sep-2024 14:43:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q3);
t3 = sin(q3);
pJ1 = [q1-t2.*2.947268971594893e-2-t3.*1.328783647639116e-1;q2-t2.*1.328783647639116e-1+t3.*2.947268971594893e-2];
end
