function pJ2 = pJ2(in1)
%pJ2
%    pJ2 = pJ2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Sep-2024 14:43:06

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q3);
t3 = cos(q4);
t4 = sin(q3);
t5 = sin(q4);
pJ2 = [q1-t2.*2.947268971594893e-2-t4.*1.328783647639116e-1-t2.*t5.*(1.1e+1./5.0e+1)-t3.*t4.*(1.1e+1./5.0e+1);q2-t2.*1.328783647639116e-1+t4.*2.947268971594893e-2-t2.*t3.*(1.1e+1./5.0e+1)+t4.*t5.*(1.1e+1./5.0e+1)];
end
