function xyInitFromAngles = xyInitFromAngles(in1,in2)
%xyInitFromAngles
%    xyInitFromAngles = xyInitFromAngles(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Sep-2024 14:43:39

PF11 = in1(1,:);
PF12 = in1(2,:);
q3 = in2(1,:);
q4 = in2(2,:);
q5 = in2(3,:);
q6 = in2(4,:);
t2 = q3+q4;
t4 = 3.269556544854363e+1;
t5 = 1.961518321693765e+16;
t3 = q5+t2;
xyInitFromAngles = [PF11+sin(t2).*(1.1e+1./5.0e+1)+sin(t3).*(1.1e+1./5.0e+1)+(t5.*cos(q3-atan(4.508525215871473)))./1.441151880758559e+17-t4.*cos(q6+t3+atan(1.3e+1./3.0e+1)).*(3.0./1.0e+3);PF12+cos(t2).*(1.1e+1./5.0e+1)+cos(t3).*(1.1e+1./5.0e+1)+t4.*cos(q6+t3-atan(3.0e+1./1.3e+1)).*(3.0./1.0e+3)+(t5.*cos(q3+atan(2.218020199775472e-1)))./1.441151880758559e+17];
end
