function CMat = C(in1)
%C
%    CMat = C(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    12-Dec-2024 14:38:42

dq2 = in1(4,:);
q2 = in1(2,:);
t2 = sin(q2);
CMat = [dq2.^2.*t2.*(3.0./5.0e+1);t2.*(-5.886e-1)];
end
