function M = M(in1)
%M
%    M = M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    12-Dec-2024 14:38:42

q2 = in1(2,:);
t2 = cos(q2);
t3 = t2.*(3.0./5.0e+1);
t4 = -t3;
M = reshape([6.0./5.0,t4,t4,9.0./5.0e+2],[2,2]);
end
