function p0 = p0(in1,dt)
%P0
%    P0 = P0(IN1,DT)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    12-Dec-2024 14:38:42

dq1 = in1(3,:);
dq2 = in1(4,:);
q2 = in1(2,:);
t2 = cos(q2);
t3 = sin(q2);
p0 = [dq1.*(6.0./5.0)-dq2.*t2.*(3.0./5.0e+1);dq2.*(9.0./5.0e+2)-dq1.*t2.*(3.0./5.0e+1)-(dt.*(t3.*5.886e-1+dq1.*dq2.*t3.*(3.0./5.0e+1)))./2.0];
end
