function out1 = pCart(in1)
%pCart
%    OUT1 = pCart(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    12-Dec-2024 14:38:41

q1 = in1(1,:);
out1 = [q1;0.0;0.0];
end
