function out1 = pPole(in1)
%pPole
%    OUT1 = pPole(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    12-Dec-2024 14:38:42

q1 = in1(1,:);
q2 = in1(2,:);
out1 = [q1-sin(q2).*(3.0./1.0e+1);0.0;cos(q2).*(3.0./1.0e+1)];
end
